In [1]:
import numpy as np

In [2]:
np.set_printoptions(suppress=True,linewidth=100,precision=2)

In [3]:
raw_data_np=np.genfromtxt("C:/Users/Sai Sailesh/Downloads/loan-data.csv",delimiter=";",skip_header=1,autostrip=True)
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [4]:
np.isnan(raw_data_np).sum()

88005

In [5]:
temporary_fill=np.nanmax(raw_data_np)+1
temporary_mean=np.nanmean(raw_data_np,axis=0)

C:\Users\Sai Sailesh\AppData\Local\Temp\ipykernel_7280\2970112798.py:2: RuntimeWarning: Mean of empty slice
  temporary_mean=np.nanmean(raw_data_np,axis=0)


In [6]:
temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [7]:
temporary_stats=np.array([np.nanmin(raw_data_np,axis=0),temporary_mean,np.nanmax(raw_data_np,axis=0)])

C:\Users\Sai Sailesh\AppData\Local\Temp\ipykernel_7280\4187671863.py:1: RuntimeWarning: All-NaN slice encountered
  temporary_stats=np.array([np.nanmin(raw_data_np,axis=0),temporary_mean,np.nanmax(raw_data_np,axis=0)])


In [8]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [9]:
columns_string=np.argwhere(np.isnan(temporary_mean)).squeeze()
print(columns_string)

[ 1  3  5  8  9 10 11 12]


In [10]:
columns_number=np.argwhere(np.isnan(temporary_mean)==False).squeeze()
columns_number

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [11]:
loan_data_string=np.genfromtxt("C:/Users/Sai Sailesh/Downloads/loan-data.csv",
                               delimiter=";",
                               skip_header=1,
                               autostrip=True,
                               usecols=columns_string,
                               dtype=np.str_)
print(loan_data_string)

[['May-15' 'Current' '36 months' ... 'Verified'
  'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226' 'CA']
 ['' 'Current' '36 months' ... 'Source Verified'
  'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261' 'NY']
 ['Sep-15' 'Current' '36 months' ... 'Verified'
  'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726' 'PA']
 ...
 ['Jun-15' 'Current' '36 months' ... 'Source Verified'
  'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990' 'CA']
 ['Apr-15' 'Current' '36 months' ... 'Source Verified'
  'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151' 'OH']
 ['Dec-15' 'Current' '36 months' ... ''
  'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249' 'IL']]


In [12]:
loan_data_number=np.genfromtxt("C:/Users/Sai Sailesh/Downloads/loan-data.csv",
                               delimiter=";",
                               skip_header=1,
                               autostrip=True,
                               usecols=columns_number,
                               filling_values=temporary_fill)
loan_data_number

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [13]:
header_full=np.genfromtxt("C:/Users/Sai Sailesh/Downloads/loan-data.csv",
                               delimiter=";",
                               skip_footer=raw_data_np.shape[0],
                               autostrip=True,
                               dtype=np.str_)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [14]:
header_string,header_number=header_full[columns_string],header_full[columns_number]

In [15]:
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [16]:
header_number

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [17]:
def checkpoint(file_name,checkpoint_header,checkpoint_data):
    np.savez(file_name, header=checkpoint_header, data=checkpoint_data)
    checkpoint_variable=np.load(file_name+".npz")
    return checkpoint_variable

In [18]:
checkpoint_test=checkpoint("checkpoint_test",header_string,loan_data_string)
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [19]:
checkpoint_test=checkpoint("checkpoint_test",header_string,loan_data_string)
checkpoint_test['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [20]:
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [21]:
header_string[0]="issue_date"

In [22]:
header_string

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [23]:
loan_data_string

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [24]:
loan_data_string[:,0]=np.chararray.strip(loan_data_string[:,0],"-15")

In [25]:
np.unique(loan_data_string[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [26]:
np.unique(loan_data_string[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [27]:
months=np.array(['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])
months

array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      dtype='<U3')

In [28]:
for i in range(13):
    loan_data_string[:,0]=np.where(loan_data_string[:,0]==months[i],
                                   i,
                                   loan_data_string[:,0])

In [29]:
np.unique(loan_data_string[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [30]:
header_string

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [31]:
np.unique(loan_data_string[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [32]:
np.unique(loan_data_string[:,1]).size

9

In [33]:
status_bad=np.array(['','Charged Off','Default','Late (31-120 days)'])

In [34]:
status_bad

array(['', 'Charged Off', 'Default', 'Late (31-120 days)'], dtype='<U18')

In [35]:
loan_data_string[:,1]=np.where(np.isin(loan_data_string[:,1],status_bad),0,1)

In [36]:
np.unique(loan_data_string[:,1])

array(['0', '1'], dtype='<U69')

In [37]:
header_string

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [38]:
loan_data_string[:,2]

array(['36 months', '36 months', '36 months', ..., '36 months', '36 months', '36 months'],
      dtype='<U69')

In [39]:
np.unique(loan_data_string[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [40]:
loan_data_string[:,2]=np.chararray.strip(loan_data_string[:,2], 'months')
loan_data_string[:,2]


array(['36 ', '36 ', '36 ', ..., '36 ', '36 ', '36 '], dtype='<U69')

In [41]:
np.unique(loan_data_string[:,2])

array(['', '36 ', '60 '], dtype='<U69')

In [42]:
loan_data_string[:,2]=np.where(loan_data_string[:,2]=='',
                               '60',
                               loan_data_string[:,2])
loan_data_string[:,2]
                               

array(['36 ', '36 ', '36 ', ..., '36 ', '36 ', '36 '], dtype='<U69')

In [43]:
np.unique(loan_data_string[:,2])

array(['36 ', '60', '60 '], dtype='<U69')

In [44]:
header_string

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [45]:
loan_data_string[:,3]

array(['C', 'A', 'B', ..., 'A', 'D', 'A'], dtype='<U69')

In [46]:
np.unique(loan_data_string[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [47]:
np.unique(loan_data_string[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [48]:
for i in np.unique(loan_data_string[:,3])[1:]:
    loan_data_string[:,4]=np.where((loan_data_string[:,4]=='') &(loan_data_string[:,3]==i),
                                   i+ '5',
                                   loan_data_string[:,4])

In [49]:
np.unique(loan_data_string[:,4],return_counts=True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [50]:
loan_data_string[:,4]=np.where((loan_data_string[:,4]==''),
                                'H5',
                                loan_data_string[:,4])

In [51]:
np.unique(loan_data_string[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H5'], dtype='<U69')

In [52]:
loan_data_string=np.delete(loan_data_string,3,axis=1)

In [53]:
loan_data_string[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [54]:
header_string=np.delete(header_string,3,)

In [55]:
header_string[3]

'sub_grade'

In [56]:
np.unique(loan_data_string[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H5'], dtype='<U69')

In [57]:
keys=list(np.unique(loan_data_string[:,3]))
values=list(range(1,np.unique(loan_data_string[:,3]).shape[0]+1))
dict_sub_grade=dict(zip(keys,values))          

In [58]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H5': 36}

In [59]:
for i in np.unique(loan_data_string[:,3]):
        loan_data_string[:,3]=np.where(loan_data_string[:,3]==i,
                                       dict_sub_grade[i],
                                       loan_data_string[:,3])

In [60]:
np.unique(loan_data_string[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [61]:
header_string

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [62]:
np.unique(loan_data_string[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [63]:
loan_data_string[:,4]=np.where((loan_data_string[:,4]=='') | (loan_data_string[:,4]=='Not Verified'),0,1)

In [64]:
np.unique(loan_data_string[:,4])

array(['0', '1'], dtype='<U69')

In [65]:
loan_data_string[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [66]:
np.chararray.strip(loan_data_string[:,5],"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
          dtype='<U69')

In [67]:
loan_data_string[:,5]=np.chararray.strip(loan_data_string[:,5],"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [68]:
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [69]:
loan_data_number[:,0].astype(np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [70]:
loan_data_string[:,5].astype(np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [71]:
loan_data_string=np.delete(loan_data_string,5,axis=1)
header_string=np.delete(header_string,5)

In [72]:
loan_data_string[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [73]:
header_string

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [74]:
loan_data_number[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [75]:
header_number

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [76]:
header_string

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [77]:
header_string[5]="state_address"

In [78]:
header_string

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'state_address'],
      dtype='<U19')

In [79]:
np.unique(loan_data_string[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [80]:
np.unique(loan_data_string[:,5],return_counts=True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27], dtype=int64))

In [81]:
states_names,states_count=np.unique(loan_data_string[:,5],return_counts=True)
states_count_sorted=np.argsort(-states_count)
states_names[states_count_sorted],states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

In [82]:
loan_data_string[:,5]=np.where((loan_data_string[:,5])=='',
                               0,
                               loan_data_string[:,5])


In [83]:
states_west = np.array(['WA', 'OR', 'CA', 'NV', 'ID', 'MT', 'WY', 'UT', 'CO', 'AZ', 'NM', 'HI', 'AK'])
states_south = np.array(['TX', 'OK', 'AR', 'LA', 'MS', 'AL', 'TN', 'KY', 'FL', 'GA', 'SC', 'NC', 'VA', 'WV', 'MD', 'DE', 'DC'])
states_midwest = np.array(['ND', 'SD', 'NE', 'KS', 'MN', 'IA', 'MO', 'WI', 'IL', 'IN', 'MI', 'OH'])
states_east = np.array(['PA', 'NY', 'NJ', 'CT', 'MA', 'VT', 'NH', 'ME', 'RI'])

In [84]:
loan_data_string[:,5]=np.where(np.isin(loan_data_string[:,5],states_west),1,loan_data_string[:,5])
loan_data_string[:,5]=np.where(np.isin(loan_data_string[:,5],states_south),2,loan_data_string[:,5])
loan_data_string[:,5]=np.where(np.isin(loan_data_string[:,5],states_midwest),3,loan_data_string[:,5])
loan_data_string[:,5]=np.where(np.isin(loan_data_string[:,5],states_east),4,loan_data_string[:,5])

In [85]:
np.unique(loan_data_string[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

In [86]:
loan_data_string

array([['5', '1', '36 ', '13', '1', '1'],
       ['0', '1', '36 ', '5', '1', '4'],
       ['9', '1', '36 ', '10', '1', '4'],
       ...,
       ['6', '1', '36 ', '5', '1', '1'],
       ['4', '1', '36 ', '17', '1', '3'],
       ['12', '1', '36 ', '4', '0', '3']], dtype='<U69')

In [87]:
loan_data_string=loan_data_string.astype(np.int32)
loan_data_string

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [88]:
checkpoint_strings=checkpoint("chechpoint_strings",header_string,loan_data_string)
checkpoint_strings["header"]


array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'state_address'],
      dtype='<U19')

In [89]:
checkpoint_strings["data"]

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [90]:
np.array_equal(checkpoint_strings["data"],loan_data_string)

True

In [91]:
print('now we gonna convert numeric to non numeric to clean and prepocess the data')

now we gonna convert numeric to non numeric to clean and prepocess the data


In [92]:
loan_data_number

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [93]:
np.isnan(loan_data_number).sum()

0

In [94]:
header_number

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [95]:
temporary_fill

68616520.0

In [96]:
np.isin(loan_data_number[:,0],temporary_fill)

array([False, False, False, ..., False, False, False])

In [97]:
np.isin(loan_data_number[:,0],temporary_fill).sum()

0

In [98]:
 header_number

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [99]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [100]:
temporary_stats[:,columns_number]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [101]:
loan_data_number[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [102]:
loan_data_number[:,2]=np.where(loan_data_number[:,2]==temporary_fill,
                               temporary_stats[0,columns_number[2]],
                               loan_data_number[:,2])
loan_data_number[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [103]:
temporary_stats[0,columns_number[3]]

6.0

In [104]:
header_number

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [105]:
for i in [1,3,4,5]:
    loan_data_number[:,i]=np.where(loan_data_number[:,i]==temporary_fill,
                               temporary_stats[2,columns_number[i]],
                               loan_data_number[:,i])
    
loan_data_number

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

In [106]:
eur_usd=np.genfromtxt("C:/Users/Sai Sailesh/Downloads/EUR-USD.csv",delimiter=',',skip_header=1,usecols=3)
eur_usd

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [107]:
np.unique(loan_data_string[:,0])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [108]:
exchange_rate=loan_data_string[:,0]
for i in range(1,13):
    exchange_rate=np.where(exchange_rate==i,
                           eur_usd[i-1],
                           exchange_rate)
exchange_rate=np.where(exchange_rate==0,
                       np.mean(eur_usd),
                       exchange_rate)
                           

np.unique(exchange_rate)

array([1.06, 1.08, 1.09, 1.09, 1.1 , 1.1 , 1.11, 1.11, 1.12, 1.12, 1.13, 1.13, 1.13])

In [109]:
exchange_rate.shape

(10000,)

In [110]:
loan_data_number.shape

(10000, 6)

In [111]:
exchange_rate=np.reshape(exchange_rate,(10000,1))
exchange_rate

array([[1.1 ],
       [1.11],
       [1.13],
       ...,
       [1.12],
       [1.11],
       [1.09]])

In [112]:
loan_data_number=np.hstack((loan_data_number,exchange_rate))
loan_data_number

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [113]:
header_number=np.concatenate((header_number,np.array(['exchange_rate'])))
header_number

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [114]:
header_number 

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [115]:
columns_dollar=np.array([1,2,4,5])

In [116]:
loan_data_number[:,[columns_dollar]]

array([[[35000.  , 35000.  ,  1184.86,  9452.96]],

       [[30000.  , 30000.  ,   938.57,  4679.7 ]],

       [[15000.  , 15000.  ,   494.86,  1969.83]],

       ...,

       [[10000.  , 10000.  ,  1372.97,  2185.64]],

       [[35000.  , 10000.  ,   354.3 ,  3199.4 ]],

       [[10000.  , 10000.  ,   309.97,   301.9 ]]])

In [117]:
loan_data_number[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [118]:
for i in columns_dollar:
    loan_data_number=np.hstack((loan_data_number,np.reshape(loan_data_number[:,i] / loan_data_number[:,6],(10000,1))))
loan_data_number

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [119]:
loan_data_number.shape

(10000, 11)

In [120]:
loan_data_number

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [121]:
header_additional=np.array([column_name+'_EUR' for column_name in header_number[columns_dollar]])
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [122]:
header_number=np.concatenate((header_number,header_additional))
header_number

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [123]:
header_number[columns_dollar]=np.array([column_name+'_USD' for column_name in header_number[columns_dollar]])
header_number

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [124]:
columns_index_order=[0,1,7,2,8,3,4,9,5,10,6]

In [125]:
header_number=header_number[columns_index_order]
header_number

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [126]:
loan_data_number

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [127]:
loan_data_nummber=loan_data_number[columns_index_order]
loan_data_number

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [128]:
header_number

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [129]:
loan_data_number[:,5]

array([9452.96, 4679.7 , 1969.83, ..., 2185.64, 3199.4 ,  301.9 ])

In [130]:
loan_data_number[:,5]=loan_data_number[:,5]/100

In [131]:
loan_data_number[:,5]

array([94.53, 46.8 , 19.7 , ..., 21.86, 31.99,  3.02])

In [132]:
checkpoint_number=checkpoint("Checkpoint-Numeric",header_number,loan_data_number)

In [133]:
checkpoint_number['header'],checkpoint_number['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
        [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
        [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
        ...,
        [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
        [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
        [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]]))

In [134]:
checkpoint_strings['data'].shape

(10000, 6)

In [135]:
checkpoint_number['data'].shape

(10000, 11)

In [136]:
loan_data=np.hstack((checkpoint_number['data'],checkpoint_strings['data']))
loan_data

array([[48010226.,    35000.,    35000., ...,       13.,        1.,        1.],
       [57693261.,    30000.,    30000., ...,        5.,        1.,        4.],
       [59432726.,    15000.,    15000., ...,       10.,        1.,        4.],
       ...,
       [50415990.,    10000.,    10000., ...,        5.,        1.,        1.],
       [46154151.,    35000.,    10000., ...,       17.,        1.,        3.],
       [66055249.,    10000.,    10000., ...,        4.,        0.,        3.]])

In [137]:
np.isnan(loan_data).sum()

0

In [138]:
header_full=np.concatenate((checkpoint_strings['header'],checkpoint_number['header']))
header_full

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'state_address',
       'id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [139]:
loan_data[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [140]:
np.argsort(loan_data[:,0])

array([2086, 4812, 2353, ..., 4935, 9388, 8415], dtype=int64)

In [141]:
loan_data=loan_data[np.argsort(loan_data[:,0])]

In [142]:
loan_data

array([[  373332.,     9950.,     1000., ...,       21.,        0.,        1.],
       [  575239.,    12000.,    12000., ...,       25.,        1.,        2.],
       [  707689.,    10000.,    10000., ...,       13.,        1.,        0.],
       ...,
       [68614880.,     5600.,     5600., ...,        8.,        1.,        1.],
       [68615915.,     4000.,     4000., ...,       10.,        1.,        2.],
       [68616519.,    21600.,    21600., ...,        3.,        0.,        2.]])

In [143]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

In [144]:
loan_data=np.vstack((header_full,loan_data))
loan_data

array([['issue_date', 'loan_status', 'term', ..., 'total_pymnt_USD', 'total_pymnt_EUR',
        'exchange_rate'],
       ['373332.0', '9950.0', '1000.0', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '12000.0', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5600.0', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '4000.0', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '21600.0', ..., '3.0', '0.0', '2.0']], dtype='<U32')

In [145]:
np.savetxt("loan-data-preproceesed.csv",loan_data,
           fmt="%s",
           delimiter=',')